# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1299, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1291, 631))
        self.widget.setStyleSheet(" QWidget#widget{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0.0150273, y1:0.108, x2:0.955, y2:0.852591, stop:0 rgba(1, 17, 165, 255), stop:0.97037 rgba(1, 17, 250, 255));}")
        self.widget.setObjectName("widget")
        self.btn_try = QtWidgets.QPushButton(self.widget)
        self.btn_try.setGeometry(QtCore.QRect(150, 200, 151, 30))
        self.btn_try.setStyleSheet("font-size:16px;\n"
"background-color: #FACB1B;")
        self.btn_try.setObjectName("btn_try")
        self.prueba = QtWidgets.QPushButton(self.widget)
        self.prueba.setGeometry(QtCore.QRect(150, 310, 321, 51))
        self.prueba.setStyleSheet("font-size:20px;\n"
"background-color:#D90728;")
        self.prueba.setObjectName("prueba")
        self.add_signal = QtWidgets.QPushButton(self.centralwidget)
        self.add_signal.setGeometry(QtCore.QRect(490, 680, 75, 23))
        self.add_signal.setObjectName("add_signal")
        self.local_port = QtWidgets.QLabel(self.centralwidget)
        self.local_port.setGeometry(QtCore.QRect(610, 680, 100, 30))
        self.local_port.setStyleSheet("font-size: 16px;\n"
"color:#fff;")
        self.local_port.setObjectName("local_port")
        self.local_port_contenido = QtWidgets.QLabel(self.centralwidget)
        self.local_port_contenido.setGeometry(QtCore.QRect(710, 670, 150, 30))
        self.local_port_contenido.setStyleSheet("font-size: 16px;\n"
"color:yellow;")
        self.local_port_contenido.setObjectName("local_port_contenido")
        self.ecu_port = QtWidgets.QLabel(self.centralwidget)
        self.ecu_port.setGeometry(QtCore.QRect(610, 710, 80, 30))
        self.ecu_port.setStyleSheet("font-size: 16px;\n"
"color:#fff;")
        self.ecu_port.setObjectName("ecu_port")
        self.ecu_port_contenido = QtWidgets.QLabel(self.centralwidget)
        self.ecu_port_contenido.setGeometry(QtCore.QRect(700, 700, 150, 30))
        self.ecu_port_contenido.setStyleSheet("font-size: 16px;\n"
"color:yellow;")
        self.ecu_port_contenido.setObjectName("ecu_port_contenido")
        self.esmart_por = QtWidgets.QLabel(self.centralwidget)
        self.esmart_por.setGeometry(QtCore.QRect(600, 740, 120, 30))
        self.esmart_por.setStyleSheet("font-size: 16px;\n"
"color:#fff;")
        self.esmart_por.setObjectName("esmart_por")
        self.esmart_port_contenido = QtWidgets.QLabel(self.centralwidget)
        self.esmart_port_contenido.setGeometry(QtCore.QRect(750, 730, 150, 30))
        self.esmart_port_contenido.setStyleSheet("font-size: 16px;\n"
"color:yellow;")
        self.esmart_port_contenido.setObjectName("esmart_port_contenido")
        self.local_ip = QtWidgets.QLabel(self.centralwidget)
        self.local_ip.setGeometry(QtCore.QRect(20, 680, 80, 30))
        self.local_ip.setStyleSheet("font-size: 16px;\n"
"color:#fff;")
        self.local_ip.setObjectName("local_ip")
        self.local_ip_contenido = QtWidgets.QLabel(self.centralwidget)
        self.local_ip_contenido.setGeometry(QtCore.QRect(110, 680, 450, 30))
        self.local_ip_contenido.setStyleSheet("font-size: 16px;\n"
"color:yellow;")
        self.local_ip_contenido.setObjectName("local_ip_contenido")
        self.detected_local = QtWidgets.QLabel(self.centralwidget)
        self.detected_local.setGeometry(QtCore.QRect(20, 710, 51, 40))
        self.detected_local.setStyleSheet("font-size: 20px;\n"
"color:#fff;")
        self.detected_local.setObjectName("detected_local")
        self.local_icon = QtWidgets.QPushButton(self.centralwidget)
        self.local_icon.setGeometry(QtCore.QRect(100, 710, 40, 40))
        self.local_icon.setStyleSheet("background-color:rgba(1, 17, 165, 255);")
        self.local_icon.setText("")
        self.local_icon.setObjectName("local_icon")
        self.detected_ecu = QtWidgets.QLabel(self.centralwidget)
        self.detected_ecu.setGeometry(QtCore.QRect(140, 710, 40, 40))
        self.detected_ecu.setStyleSheet("font-size: 20px;\n"
"color:#fff;")
        self.detected_ecu.setObjectName("detected_ecu")
        self.detected_esmart = QtWidgets.QLabel(self.centralwidget)
        self.detected_esmart.setGeometry(QtCore.QRect(230, 710, 71, 40))
        self.detected_esmart.setStyleSheet("font-size: 20px;\n"
"color:#fff;")
        self.detected_esmart.setObjectName("detected_esmart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BACHET Tool"))
        self.btn_try.setText(_translate("MainWindow", "try / Start Server"))
        self.prueba.setText(_translate("MainWindow", "PushButton"))
        self.add_signal.setText(_translate("MainWindow", "Add Signal"))
        self.local_port.setText(_translate("MainWindow", "Local Port:"))
        self.local_port_contenido.setText(_translate("MainWindow", "-------------------------------------------------------------"))
        self.ecu_port.setText(_translate("MainWindow", "ecu Port:"))
        self.ecu_port_contenido.setText(_translate("MainWindow", "-------------------------------------------------------------"))
        self.esmart_por.setText(_translate("MainWindow", "eSmart Port:"))
        self.esmart_port_contenido.setText(_translate("MainWindow", "-------------------------------------------------------------"))
        self.local_ip.setText(_translate("MainWindow", "Local Ip: "))
        self.local_ip_contenido.setText(_translate("MainWindow", "-------------------------------------------------------------"))
        self.detected_local.setText(_translate("MainWindow", "Local"))
        self.detected_ecu.setText(_translate("MainWindow", "ECU"))
        self.detected_esmart.setText(_translate("MainWindow", "eSmart"))
